In [ ]:
import numpy as np

np.random.seed(42)

array = np.random.randint(1, 51, size=(5, 4))
print("Generated Array:")
print(array)


Generated Array:
[[39 29 15 43]
 [ 8 21 39 19]
 [23 11 11 24]
 [36 40 24  3]
 [22  2 24 44]]


In [ ]:
anti_diagonal = []
rows, cols = array.shape
for i in range(min(rows, cols)):
    row_idx = i
    col_idx = cols - 1 - i
    anti_diagonal.append(array[row_idx, col_idx])
print (anti_diagonal)

[np.int64(43), np.int64(39), np.int64(11), np.int64(36)]


In [ ]:
row_maxes = np.max(array, axis=1)
print(row_maxes)

[43 39 24 40 44]


In [ ]:
overall_mean = np.mean(array)
print(overall_mean)
elements_le_mean = array[array <= overall_mean]
print(elements_le_mean)


23.85
[15  8 21 19 23 11 11  3 22  2]


In [ ]:
def numpy_boundary_traversal(matrix):

    if matrix.size == 0:
        return []

    rows, cols = matrix.shape
    boundary_elements = []

    if rows == 1:
        return matrix[0].tolist()

    if cols == 1:
        return matrix[:, 0].tolist()

    boundary_elements.extend(matrix[0, :].tolist())

    boundary_elements.extend(matrix[1:rows, cols-1].tolist())

    if rows > 1:
        boundary_elements.extend(matrix[rows-1, cols-2::-1].tolist())

    if cols > 1:
        boundary_elements.extend(matrix[rows-2:0:-1, 0].tolist())

    return boundary_elements


In [ ]:
numpy_boundary_traversal(array)

[39, 29, 15, 43, 19, 24, 3, 44, 24, 2, 22, 36, 23, 8]